### ISSUE TITLE
Custom delete confirmation

### ISSUE THREAD

**Issue by Aidurber** [Aidurber/VueTagPicker#12]
Should accept two props: 

1. confirmDelete (Boolean: defaults to false)
2. confirmDeleteCallback (Function or Promise: optional)

If confirmDelete is passed in, when a user removes a tag, a plain Javascript `confirm` dialog should appear. If the user clicks "Ok", remove the tag, cancel should not remove the tag. 

If confirmDelete and confirmDeleteCallback are supplied, the callback should be returned before removing the tag. The purpose of this one is so developers can use custom alert libraries like [SweetAlert2](https://limonte.github.io/sweetalert2/)

**Bonus points**: A third prop confirmDeleteMessage, so if confirmDelete is supplied and confirmDeleteCallback is **not** supplied, then pass the conformDeleteMessage into the plain JS confirm dialog.

**Comment by huyvohcmc** [comment]
Hi I'm working on it

**Comment by rodrigoheffner** [comment]
Hi - I'll give it a go to implement this one, if that's ok?

**Comment by Aidurber** [comment]
Hi @rodrigoheffner , 

Absolutely, give it a go. I'll add a tag "in progress" to let other developers know it's being worked on. If you decide you don't want to do it, just let me know and I'll open it back up to others. 

Let me know if you have any questions. 

Thank you! 😄

**Comment by Aidurber** [comment]
Also @rodrigoheffner , I've just added notes on contributing to the README

**Comment by rodrigoheffner** [comment]
Thanks, @Aidurber !

**Comment by rodrigoheffner** [comment]
@Aidurber sorry but I'm a bit of a Vue noob and I'm having issues changing the default value of properties when calling the component's constructor. For example https://jsfiddle.net/vLb79yp1/1/ does not change the default value of "allowDuplicates" - can you share a jsfiddle which you can do that when you have a moment? On the meantime I'll continue developing locally with the new "confirmDelete" property with a default of true

**Comment by Aidurber** [comment]
@rodrigoheffner No need to apologise!
So on the JSFiddle, we are just creating a new Vue instance for the div "app", not the TagPicker. Changing the default values occurs in TagPicker.vue (not in the Fiddle), see here: https://github.com/Aidurber/VueTagPicker/blob/master/src/components/TagPicker.vue#L34

Passing in props occurs in the DOM: 
`<tag-picker  :allow-duplicates="true"`

If the developer doesn't include that property, it falls back to the default value specified in the props object on the Tag Picker i.e.:

```js
export default {
  name: 'tag-picker',
  props: {
    //Allow duplicate tags
    allowDuplicates: {
      type: Boolean,
      default: false
    },
    seperator: {
      type: String,
      default: "|"
    },
```

So in your case if you wanted a confirm delete prop, you would add a new object to the props object
```js
//other props...
 confirmDelete: {
    type: Boolean,
    default: false
 }
```

or if you wanted confirmDelete to be true by default, set `default: true`

This section in the Vue.js documentation covers it: https://vuejs.org/v2/guide/components.html#Prop-Validation

But again, no need to apologise, ask as many questions as you need to.

**Comment by rodrigoheffner** [comment]
@Aidurber let me know if you would like any changes to be made before merging the pull request - thanks for your thorough explanation!

**Comment by Aidurber** [comment]
As I mentioned on the pull request, good work @rodrigoheffner , and again, thank you for your hard work. 

3 more PRs in Hacktoberfest and you grab yourself a t-shirt! [Hacktoberfest Checker@rodrigoheffner](https://hacktoberfestchecker.herokuapp.com/?username=rodrigoheffner) Good luck with the rest 😀

**Comment by rodrigoheffner** [comment]
thanks @Aidurber - Also thanks again for all the explanation. It's been fun playing around with Vue and learning a bit more about it :)
